server:
  servlet:
    context-path: /portal
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    max-threads: 500
    min-spare-threads: 30
  port: 8081
logging:
  config: classpath:logback.xml
spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mcp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: your_password
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 6000
      time-between-connect-error-millis: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 50000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filter:
        commons-log:
          enabled: true
          connection-logger-name: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
    platform: mysql
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    #password: 123456Qw
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hnkylin.cloud.selfservice.domain,com.hnkylin.cloud.core.domain
  global-config:
    id-type: 0
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
auth:
  authExcludeApis:
    - /portal/api/user/register
    - /portal/api/login
    - /portal/error
    - /portal/index
    - /portal/api/org/queryOrgList
mc-config:
  mcPrefix: /kylin
  commonPrefix: /mc/api
  templateListUrl: /getTemplates
  serverVmList: /getSelfServiceVmList
  startServerVmUrl: /selfServiceVmServerStart
  shutdownServerVmUrl: /selfServiceShutDown
  forcedShutdownServerVmUrl: /selfServiceAbort
  forcedRestartServerVmUrl: /selfServiceForceReboot
  restartServerVmUrl: /selfServiceReboot
  batchStartServerVmUrl: /startSelfServiceForBatch
  batchShutdownServerVmUrl: /shutDownSelfServiceForBatch
  batchRebootServerVmUrl: /rebootForBatch
  serverVmInfoUrl: /selfServiceMachineDetailInfo
  serverVmMonitorInfoUrl: /listServerVMStatus
  serverVmOperateLogUrl: /listTasksByServerId
  serverVmSnapshotListUrl: /serverSnapshotList
  serverVmCreateSnapshotUrl: /createServerSnap
  serverVmUpdateSnapshotUrl: /updateServerSnapData
  serverVmDeleteSnapshotUrl: /deleteServerSnapshot
  serverVmApplySnapshotUrl: /applyServerBatchSnap
  serverVmVncUrl: /getServerVmVncUrl
  batchRemoveMachineToRecycleUrl: /batchRemoveMachineToRecycle
  serverVmStatusUrl: /getMachineStatus
  updateMachineDescriptionUrl: /updateMachineDescription
  resetRemotePasswordUrl: /resetRemotePassword
  getServervmDetailByServevmIdUrl: /getServervmDetailByServevmId
  logoPath: /images/hnkylin/
  isoListUrl: /isoList
  allOperatingSystemUrl: /getAllOperatingSystem
  updateMachineNameUrl: /updateMachineName
  checkVmServerNameUrl: /checkVmServerName


